#!/bin/sh

apk add parted

parted --script /dev/sdc mklabel gpt
parted --script --align=optimal /dev/sdc mkpart ESP fat32 1MiB 100%
parted --script /dev/sdc set 1 boot on

sleep 2

mkfs.vfat -n ALPINE /dev/sdc1

wget https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86_64/alpine-extended-3.20.1-x86_64.iso

sleep 2

mount -t vfat /dev/sdc1 /mnt
cd /mnt
uniso < /root/alpine-extended-3.20.1-x86_64.iso

sync

cd ~ && umount /mnt

# Per a formatar el disk principal:

# apk add e2fsprogs
# umount /media/sda1
# apk add parted
# parted /dev/sda mklabel gpt
# parted -a opt /dev/sda mkpart primary ext4 0% 100%
# mkfs.ext4 /dev/sda1